---
- name: Clone Git Repository
  hosts: localhost

  tasks:
    - git:
        repo: 'https://github.com/ervis-s/Ansible-Repository'
        dest: /tmp/test_ans2
        version: Ansible-Template
        force: yes
      register: clone

    - debug:
        msg: Il Repository locale è stato aggiornato
      when: clone.changed
